---
deployment:
  tasks:
    - /usr/local/bin/php /home/mbjmtfwx/repositories/Readpoint/backend/artisan config:clear
    - /usr/local/bin/php /home/mbjmtfwx/repositories/Readpoint/backend/artisan route:clear
    - /usr/local/bin/php /home/mbjmtfwx/repositories/Readpoint/backend/artisan view:clear
    - /usr/local/bin/php /home/mbjmtfwx/repositories/Readpoint/backend/artisan migrate --force
    - /usr/local/bin/php /home/mbjmtfwx/repositories/Readpoint/backend/artisan config:cache
    - /usr/local/bin/php /home/mbjmtfwx/repositories/Readpoint/backend/artisan route:cache
