---
deployment:
  tasks:
    - /usr/local/bin/composer install --no-dev --optimize-autoloader --no-interaction --working-dir=/home/mbjmtfwx/repositories/Readpoint/backend
    - /usr/local/bin/php /home/mbjmtfwx/repositories/Readpoint/backend/artisan config:clear
    - /usr/local/bin/php /home/mbjmtfwx/repositories/Readpoint/backend/artisan route:clear
    - /usr/local/bin/php /home/mbjmtfwx/repositories/Readpoint/backend/artisan view:clear
    - /usr/local/bin/php /home/mbjmtfwx/repositories/Readpoint/backend/artisan migrate --force
    - /usr/local/bin/php /home/mbjmtfwx/repositories/Readpoint/backend/artisan storage:link
    - /usr/local/bin/php /home/mbjmtfwx/repositories/Readpoint/backend/artisan config:cache
    - /usr/local/bin/php /home/mbjmtfwx/repositories/Readpoint/backend/artisan route:cache
