location / {
    # try to serve file directly, fallback to rewrite
    try_files $uri @rewriteapp;
}

location @rewriteapp {
    # rewrite all to app.php
    rewrite ^(.*)$ /index.php/$1 last;
}

location ~ ^/index\.php(/|$) {
    # if the request starts with our front controller, skip these checks
    try_files @heroku-fcgi @heroku-fcgi;
    internal;
}

location ~ \.php$ {
    # do not allow direct access to other php files
    return 404;
}
